#include <stdio.h>
#include <stdlib.h>
#include <math.h>

#define dim 3
#define size_dim 129
#define size (size_dim*size_dim*size_dim)

void read_turbulence(double **turb_array)
{
    printf("Reading grid turbulence file\n");
    FILE *turb_in = fopen("turbulence19.txt", "r"); /// file generated by the turbulence_generator.py
    double dummy1, dummy2, dummy3;
    int i;
    for (i=0;i<size; i++)
    {
        fscanf(turb_in, "%lf %lf %lf %lf %lf %lf\n", &dummy1, &dummy2, &dummy3, &turb_array[0][i], &turb_array[1][i], &turb_array[2][i]) ;
    }
    fclose(turb_in);
}

void normalize_turbulence(double **turb_array, double **normal_turb )
{
    printf("Normalizing energy of velocity field\n");
    int i;
    double Z=0;
    for (i=0;i<size; i++)
    {
        Z = Z + (0.5*( pow(turb_array[0][i],2.0) + pow(turb_array[1][i],2.0) + pow(turb_array[2][i],2.0) ) );
    }
    int j; double z0=0;
    for (j=0;j<size;j++)
    {
        normal_turb[0][j] = turb_array[0][j] / sqrt(Z);
        normal_turb[1][j] = turb_array[1][j] / sqrt(Z);
        normal_turb[2][j] = turb_array[2][j] / sqrt(Z);
        z0 = z0 + (0.5*( pow(normal_turb[0][j],2.0) + pow(normal_turb[1][j],2.0) + pow(normal_turb[2][j],2.0) ));
    }
    printf("\tNormalization = %f\n", z0);
}

void write_turbulence(double **v_b)
{
    printf("Writing normalized turbulence\n");
    FILE *write = fopen("t19_vn_grid.txt", "w"); //// name of the file to be written
    int j;
    for (j=0;j<size; j++)
    {
        fprintf(write, "%e %e %e\n", v_b[0][j], v_b[1][j], v_b[2][j]) ;
        
    }
    fclose(write);
}

void freeArray(double **a) {
    int i;
    for (i = 0; i < dim; i++) {
        free(a[i]);
    }
    free(a);
}

int main()
{
    printf("Commencing calculation\n");
    ///-----------------------------------------------///
    ///////////////////Define arrays////////////////////
    double **v;
    double **v_normal;
    v = malloc(dim * sizeof(double *));
    v_normal = malloc(dim * sizeof(double *));
   
    if(v == NULL)
    {
        fprintf(stderr, "out of memory--v\n");
    }
    else if(v_normal == NULL)
    {
        fprintf(stderr, "out of memory--v_normal\n");
    }
    int i;
    for(i = 0; i < dim; i++)
    {
        v[i] = malloc(size * sizeof(double));
        v_normal[i] = malloc(size * sizeof(double));
		if( v[i] == NULL || v_normal[i] == NULL)
        {
			fprintf(stderr, "out of memory----\n");
        }
    }
    
    ///-----------------------------------------------///
    
    ///-----------------------------------------------///
    read_turbulence(v); //read turbulence file
    normalize_turbulence(v, v_normal); ///normalize turbulence
    write_turbulence(v_normal); // write turbulence
    ///-----------------------------------------------///
    
 
    freeArray(v); 
    freeArray(v_normal);

    printf("Calculation complete\n");
    
    
    return 0;
}
